/**
 * fetchVAASonicToSolana.ts
 *
 * Relay script: Sonic → Solana
 *
 * Usage:
 *   EMITTER=<hex_emitter_address> SEQUENCE=<number> \
 *   SOLANA_KEYPAIR=~/.config/solana/id.json \
 *   ts-node src/fetchVAASonicToSolana.ts
 *
 * What this script does:
 *  1. Fetches the signed VAA from the Wormhole Guardian API.
 *  2. Derives the required Anchor accounts.
 *  3. Calls bridge_solana.process_from_sonic with the VAA hash.
 *     (The Wormhole Solana SDK must have already posted the VAA on-chain.)
 */

import * as anchor from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  getAssociatedTokenAddressSync,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import axios from "axios";
import * as fs from "fs";
import { WORMHOLE_CONFIG, SOLANA_CONFIG, SONIC_CONFIG } from "./config";

const BRIDGE_STATE_SEED    = Buffer.from("bridge_state");
const MINT_SEED            = Buffer.from("wrapped_mint");
const CONSUMED_SEED        = Buffer.from("consumed");

async function main() {
  // ── Load inputs from env ─────────────────────────────────────────────────
  const emitter  = process.env.EMITTER  ?? SONIC_CONFIG.bridgeSonicAddress;
  const sequence = process.env.SEQUENCE ?? "0";
  const keypairPath = process.env.SOLANA_KEYPAIR ?? `${process.env.HOME}/.config/solana/id.json`;

  console.log(`Fetching VAA for emitter=${emitter} sequence=${sequence}…`);

  // ── 1. Fetch the VAA from Wormhole Guardian REST API ────────────────────
  const chainId = WORMHOLE_CONFIG.evm.wormholeChainId;
  const emitterHex = emitter.replace(/^0x/, "").toLowerCase().padStart(64, "0");
  const vaaUrl = `${WORMHOLE_CONFIG.restApi}/v1/signed_vaa/${chainId}/${emitterHex}/${sequence}`;

  const response = await axios.get<{ vaaBytes: string }>(vaaUrl);
  const vaaBase64 = response.data.vaaBytes;
  const vaaBytes  = Buffer.from(vaaBase64, "base64");

  console.log(`VAA fetched (${vaaBytes.length} bytes).`);

  // ── 2. Connect to Solana devnet ──────────────────────────────────────────
  const connection = new Connection(SOLANA_CONFIG.rpcUrl, "confirmed");
  const secretKey  = JSON.parse(fs.readFileSync(keypairPath, "utf-8"));
  const wallet     = Keypair.fromSecretKey(Uint8Array.from(secretKey));

  // ── 3. Derive PDAs ───────────────────────────────────────────────────────
  const programId = new PublicKey(SOLANA_CONFIG.programId);

  const [bridgeStatePda] = PublicKey.findProgramAddressSync(
    [BRIDGE_STATE_SEED],
    programId
  );
  const [wrappedMintPda] = PublicKey.findProgramAddressSync(
    [MINT_SEED],
    programId
  );

  // VAA hash = sha256(vaaBytes) — Wormhole convention
  const vaaHash = require("crypto")
    .createHash("sha256")
    .update(vaaBytes)
    .digest();

  const [vaaConsumedPda] = PublicKey.findProgramAddressSync(
    [CONSUMED_SEED, vaaHash],
    programId
  );

  // Derive the Wormhole posted VAA PDA
  const wormholeProgramId = new PublicKey(WORMHOLE_CONFIG.solana.coreBridgeProgramId);
  const [postedVaaPda]    = PublicKey.findProgramAddressSync(
    [Buffer.from("PostedVAA"), vaaHash],
    wormholeProgramId
  );

  // Parse recipient from VAA payload (bytes 1..32 after action byte)
  // We rely on the VAA already being posted; here we just extract the pubkey.
  // In a real implementation you would post the VAA first via the Wormhole program.
  // For this prototype we read the recipient from the raw VAA body.
  // VAA layout: header(6) + signatures(n*66) + body ...
  // For simplicity we trust the script caller to pass the recipient separately.
  const recipientEnv = process.env.RECIPIENT;
  if (!recipientEnv) {
    console.error("Set RECIPIENT=<solana pubkey> of the bridged token recipient");
    process.exit(1);
  }
  const recipient = new PublicKey(recipientEnv);
  const recipientAta = getAssociatedTokenAddressSync(wrappedMintPda, recipient);

  // ── 4. Load Anchor program and call process_from_sonic ───────────────────
  const provider = new anchor.AnchorProvider(
    connection,
    new anchor.Wallet(wallet),
    { commitment: "confirmed" }
  );
  anchor.setProvider(provider);

  // Load IDL from file (generated by `anchor build`)
  const idlPath = `${__dirname}/../../solana/target/idl/bridge_solana.json`;
  if (!fs.existsSync(idlPath)) {
    console.error(`IDL not found at ${idlPath}. Run 'anchor build' first.`);
    process.exit(1);
  }
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf-8"));
  const program = new anchor.Program(idl, provider);

  const vaaHashArr = Array.from(vaaHash) as number[];

  const tx = await (program.methods as any)
    .processFromSonic(vaaHashArr)
    .accounts({
      payer:                wallet.publicKey,
      bridgeState:          bridgeStatePda,
      postedVaa:            postedVaaPda,
      vaaConsumed:          vaaConsumedPda,
      wrappedMint:          wrappedMintPda,
      recipientTokenAccount: recipientAta,
      tokenProgram:         TOKEN_PROGRAM_ID,
      systemProgram:        SystemProgram.programId,
      rent:                 SYSVAR_RENT_PUBKEY,
    })
    .rpc();

  console.log("✅ process_from_sonic tx:", tx);
  console.log("   Recipient:", recipient.toBase58());
  console.log("   Wrapped mint:", wrappedMintPda.toBase58());
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
